### ISSUE TITLE
Where is classilla source code?

### ISSUE THREAD

**Issue by joone** [classilla/classilla#228]
I found an archive in here: https://code.google.com/archive/p/classilla/
But, it seems no source code in github.

**Comment by classilla** [comment]
The Classilla source code is currently housed on SourceForge, which is presently down with an ETA only of "tonight (PDT)."

**Comment by joone** [comment]
Okay, I've found it.

https://sourceforge.net/projects/classilla/?source=navbar

**Comment by joone** [comment]
@classilla do you have any instructions to build it?

**Comment by joone** [comment]
oh, here it is: https://github.com/classilla/classilla/blob/master/wiki/HowToBuild.wiki
